[package]
name = "hubcap"
version = "0.1.0"
authors = ["Peter Schuller <peter.schuller@infidyne.com>"]
autobins = false

[[bin]]
name = "hc"
path = "src/main.rs"

[dependencies]
clap = "2"
failure = "0.1.2"
github-rs = "0.6"
serde_json = "1.0"
