name: CI
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: git version
      run: git version

    - name: rust version
      run: rustc --version

    - name: Build
      run: cargo build

    - name: Test
      run: cargo test
