name: CI
on: [push]
jobs:
  test
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: build
      run: cargo build --release

    - name: test
      run: cargo test --verbose
